version: '3'

services:
  frontend:
    build:
      dockerfile: Dockerfile.prod
      context: ./frontend
    container_name: docker-app--frontend
    restart: unless-stopped
    command: serve -s build -l 3000
    networks:
      - docker-app--network

  api:
    build: ./api
    container_name: docker-app--api
    command: npm run start
    restart: unless-stopped
    environment:
      - PORT=3001
      - MONGO_URL=mongodb://api_db:27017/api
      - AUTH_API_URL=http://auth:3002/api
    depends_on:
      - api_db
    networks:
      - docker-app--network

  auth:
    build: ./auth
    container_name: docker-app--auth
    command: npm run start
    restart: unless-stopped
    environment:
      - PORT=3002
      - MONGO_URL=mongodb://auth_db:27017/auth
      - API_URL=http://api:3001/api
    depends_on:
      - auth_db
    networks:
      - docker-app--network

  api_db:
    image: mongo:latest
    container_name: docker-app--api-db
    volumes:
      - mongodb_api:/data/db
    networks:
      - docker-app--network

  auth_db:
    image: mongo:latest
    container_name: docker-app--auth-db
    volumes:
      - mongodb_auth:/data/db
    networks:
      - docker-app--network

  nginx:
    image: nginx:stable-alpine
    container_name: docker-app--nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend
      - api
      - auth
    networks:
      - docker-app--network

volumes:
  mongodb_api:
  mongodb_auth:

networks:
  docker-app--network:
    driver: bridge
